# This 
name: CI

# Controls when the action will run. 
on: [pull_request]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: hbaldzuhn/docker-usd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build everything in the repository
        run: |
          echo "Now building with tags: ${{ github.event.inputs.tags }}" 
          mkdir build
          cd build
          cmake3 ..
          makel
